# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            熊超
tagline:          'simon'
description:      'Xiong Chao Blog'
url:              http://xiongchao.github.io/
baseurl:          '/'
paginate:         5
timezone:         China/Beijing

author:
  name:           '熊超'
  url:            http://weibo.com/u/1660456274

# Custom vars
version:          0.0.3

github:
  repo:           https://github.com/xiongchao/xiongchao.github.io
